version: "3.9"

services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: linve-mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # UI Web
